# Generated by Django 6.0.4 on 2026-06-02 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeApp', '0002_alter_receptionist_identitydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='closingHour',
            field=models.TimeField(default=datetime.time(20, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='openingHour',
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
    ]
