# Generated by Django 6.0.4 on 2026-06-02 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeApp', '0003_office_closinghour_office_openinghour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='closingHour',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AlterField(
            model_name='office',
            name='openingHour',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
