# Generated by Django 6.0.4 on 2026-06-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeApp', '0004_alter_office_closinghour_alter_office_openinghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='mustChangePassword',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='office',
            name='identityCode',
            field=models.CharField(max_length=20),
        ),
    ]
