# Generated by Django 6.0.4 on 2026-06-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
