# Generated by Django 5.1.5 on 2026-04-26 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0002_alter_doctor_firstsurname_alter_doctor_secondsurname'),
        ('patientApp', '0002_alter_patient_firstsurname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identityCode', models.CharField(unique=True, verbose_name=20)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('sideEffects', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='timestamp',
            new_name='appointmentCreation',
        ),
        migrations.AddField(
            model_name='patient',
            name='bloodType',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='unrelatedClinicalData',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(related_name='patients', to='doctorApp.doctor'),
        ),
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='patientApp.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='patientApp.appointment')),
                ('calendarDay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='patientApp.calendarday')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('beginningDate', models.DateTimeField(auto_now_add=True)),
                ('endingDate', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='patientApp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='vaccinations',
            field=models.ManyToManyField(related_name='patients', to='patientApp.vaccine'),
        ),
    ]
