# Generated by Django 6.0.4 on 2026-06-01 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeApp', '0001_initial'),
        ('patientApp', '0002_appointment_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='officeApp.office'),
            preserve_default=False,
        ),
    ]
