# Generated by Django 6.0.4 on 2026-05-21 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0004_room_specialcode'),
        ('patientApp', '0002_patient_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='hospitalApp.hospital'),
        ),
    ]
