# Generated by Django 6.0.4 on 2026-05-22 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0004_doctor_hospital'),
        ('patientApp', '0003_patient_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarday',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='calendarhour',
            name='calendarDay',
        ),
        migrations.RemoveField(
            model_name='calendarhour',
            name='appointment',
        ),
        migrations.CreateModel(
            name='AppointmentTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning', models.DateTimeField()),
                ('ending', models.DateTimeField()),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patientApp.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorApp.doctor')),
            ],
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='CalendarDay',
        ),
        migrations.DeleteModel(
            name='CalendarHour',
        ),
    ]
