# Generated by Django 6.0.4 on 2026-05-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientApp', '0003_calendar_vaccine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='vaccinations',
            field=models.ManyToManyField(blank=True, related_name='patients', to='patientApp.vaccine'),
        ),
    ]
