# Generated by Django 6.0.4 on 2026-05-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientApp', '0004_remove_calendarday_calendar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmenttime',
            name='doctor',
        ),
    ]
