# Generated by Django 6.0.4 on 2026-06-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientApp', '0004_alter_patient_identitydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mustChangePassword',
            field=models.BooleanField(default=False),
        ),
    ]
