# Generated by Django 6.0.4 on 2026-05-22 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0004_doctor_hospital'),
        ('patientApp', '0006_remove_appointment_doctor_appointmenttime_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='vaccinations',
        ),
        migrations.AlterField(
            model_name='appointmenttime',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointmentTimes', to='doctorApp.doctor'),
        ),
    ]
