# Generated by Django 6.0.4 on 2026-05-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='identityCode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
