# Generated by Django 5.1.5 on 2026-04-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='djangoUser',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctors',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
