# Generated by Django 6.0.4 on 2026-05-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0003_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='specialCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
