# Generated by Django 6.0.4 on 2026-05-21 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_administrator_sex'),
        ('hospitalApp', '0004_room_specialcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='administrator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='adminApp.administrator'),
        ),
    ]
