# Generated by Django 6.0.4 on 2026-05-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0005_alter_hospital_administrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='department',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
