# Generated by Django 6.0.4 on 2026-05-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0006_remove_room_floor_remove_room_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='administrator',
        ),
    ]
