# Generated by Django 6.0.4 on 2026-08-15 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('primerApellido', models.CharField(blank=True, max_length=120, null=True)),
                ('segundoApellido', models.CharField(blank=True, max_length=120, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('V', 'Varón'), ('M', 'Mujer')], max_length=1, null=True)),
                ('tipoDocumento', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('NIE', 'NIE')], max_length=3, null=True)),
                ('documentoIdentidad', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('pais', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('usuarioBase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('primerApellido', models.CharField(blank=True, max_length=120, null=True)),
                ('segundoApellido', models.CharField(blank=True, max_length=120, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('V', 'Varón'), ('M', 'Mujer')], max_length=1, null=True)),
                ('tipoDocumento', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('NIE', 'NIE')], max_length=3, null=True)),
                ('documentoIdentidad', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('pais', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('grupoSanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='usersApp.aseguradora')),
                ('usuarioBase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('primerApellido', models.CharField(blank=True, max_length=120, null=True)),
                ('segundoApellido', models.CharField(blank=True, max_length=120, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('V', 'Varón'), ('M', 'Mujer')], max_length=1, null=True)),
                ('tipoDocumento', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('NIE', 'NIE')], max_length=3, null=True)),
                ('documentoIdentidad', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('pais', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('usuarioBase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
