# Generated by Django 6.0.4 on 2026-10-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_aseguradora_administrador_paciente_recepcionista'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepcionista',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
