# Generated by Django 6.0.4 on 2026-05-28 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('firstSurname', models.CharField(blank=True, max_length=120, null=True)),
                ('secondSurname', models.CharField(blank=True, max_length=120, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('identityDocument', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postCode', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('djangoUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
