# Generated by Django 6.0.4 on 2026-05-23 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0001_initial'),
        ('hospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='hospitalApp.hospital'),
        ),
    ]
