# Generated by Django 6.0.4 on 2026-05-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0001_initial'),
        ('officeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='office',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='officeApp.office'),
        ),
    ]
