# Generated by Django 5.1.5 on 2026-04-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('firstSurname', models.CharField(max_length=120)),
                ('secondSurname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('identityDocument', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postCode', models.IntegerField(max_length=15)),
                ('country', models.CharField(max_length=100)),
                ('telephone', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
