# Generated by Django 6.0.4 on 2026-06-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='identityDocument',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
