# Generated by Django 6.0.4 on 2026-05-22 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_administrator_sex'),
        ('hospitalApp', '0007_remove_hospital_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='hospitalApp.hospital'),
        ),
    ]
