# Generated by Django 6.0.4 on 2026-05-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_initial'),
        ('hospitalApp', '0002_receptionist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.hospital'),
        ),
    ]
