# Generated by Django 5.1.5 on 2026-04-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_alter_administrator_djangouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='postCode',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
