# Generated by Django 5.1.5 on 2026-04-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0006_alter_administrator_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='firstSurname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='secondSurname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
