# Generated by Django 5.1.5 on 2026-04-18 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('firstSurname', models.CharField(max_length=120)),
                ('secondSurname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('identityDocument', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postCode', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('educationalBackground', models.TextField(max_length=500)),
                ('cv', models.FileField(upload_to='')),
                ('djangoUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
