# Generated by Django 6.0.4 on 2026-05-23 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorApp', '0001_initial'),
        ('hospitalApp', '0001_initial'),
        ('patientApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ManyToManyField(related_name='doctors', to='hospitalApp.hospital'),
        ),
        migrations.AddField(
            model_name='report',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patientApp.appointment'),
        ),
        migrations.AddField(
            model_name='report',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='doctorApp.doctor'),
        ),
        migrations.AddField(
            model_name='report',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hospitalApp.hospital'),
        ),
        migrations.AddField(
            model_name='report',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patientApp.incident'),
        ),
        migrations.AddField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patientApp.patient'),
        ),
    ]
