# Generated by Django 5.1.5 on 2026-04-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='firstSurname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='secondSurname',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
