# Generated by Django 6.0.4 on 2026-05-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0002_alter_doctor_firstsurname_alter_doctor_secondsurname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
