# Generated by Django 6.0.4 on 2026-05-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
