# Generated by Django 6.0.4 on 2026-05-21 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0003_doctor_sex_alter_vaccine_identitycode'),
        ('hospitalApp', '0004_room_specialcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospitalApp.hospital'),
        ),
    ]
