# Generated by Django 6.0.4 on 2026-05-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0004_doctor_hospital'),
        ('hospitalApp', '0006_remove_room_floor_remove_room_department_and_more'),
        ('patientApp', '0007_remove_patient_vaccinations_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaccine',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ManyToManyField(related_name='doctors', to='hospitalApp.hospital'),
        ),
    ]
