# Generated by Django 6.0.4 on 2026-08-27 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='appointmentsApp.calendario')),
            ],
        ),
    ]
