# Generated by Django 6.0.4 on 2026-10-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentsApp', '0002_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_asistio', 'No asistió')], default='pendiente', max_length=20),
        ),
    ]
